services:
  - type: web
    name: secret-santa-menu
    env: python
    plan: free
    buildCommand: "python -m pip install -U pip && pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
    healthCheckPath: /health
